---
  - hosts: elk
    become: True
    tasks:
    
    - sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        
    - name: docker.io
      apt:
        update-chache: yes
        name: docker.io
        state: present
        
    - name: Install Python3
      apt:
        name: python3-pip
        state: present
    
    - name: Install pip
      pip:
        name: docker
        state: present
        
    - name: Download and launch docker web container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
         - "5601:5601"
         - "9200:9200"
         - "5044:5044"
     
     - name: Enab;e docker service
       systemd:
         name: docker
         enabled: yes
